services:
  postgres:
    image: postgres:16.11-alpine
    container_name: gov_postgress
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forge_api
    ports:
      - "5432:5432"
    volumes:
      - forge_api:/var/lib/postgresql/data
      
volumes:
  forge_api: