/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login": {
    /** Authenticate a user and return access and refresh tokens */
    post: {
      parameters: {
        body: {
          /** Login credentials */
          body: definitions["auth.LoginRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["auth.AuthResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["utils.Error"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["utils.Error"];
        };
      };
    };
  };
  "/auth/signup": {
    /** Register a new user and return access and refresh tokens */
    post: {
      parameters: {
        body: {
          /** Signup details */
          body: definitions["auth.SignupRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["auth.AuthResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["utils.Error"];
        };
        /** Conflict */
        409: {
          schema: definitions["utils.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["utils.Error"];
        };
      };
    };
  };
  "/health": {
    /** Returns API liveness status */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["health.HealthResponse"];
        };
      };
    };
  };
  "/health/ready": {
    /** Returns API and dependency readiness status */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["health.ReadinessResponse"];
        };
        /** Service Unavailable */
        503: {
          schema: definitions["health.ReadinessResponse"];
        };
      };
    };
  };
  "/task": {
    /** Create a new task for the authenticated user */
    post: {
      parameters: {
        body: {
          /** Task details */
          body: definitions["tasks.CreateTaskRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["tasks.TaskResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["utils.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["utils.Error"];
        };
      };
    };
  };
  "/task/{id}": {
    /** Delete a task by ID for the authenticated user */
    delete: {
      parameters: {
        path: {
          /** Task ID */
          id: string;
        };
      };
      responses: {
        /** No Content */
        204: {
          schema: definitions["tasks.TaskResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["utils.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["utils.Error"];
        };
      };
    };
  };
  "/tasks": {
    /** Retrieve all tasks for the authenticated user */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["tasks.TaskResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["utils.Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["utils.Error"];
        };
      };
    };
  };
}

export interface definitions {
  "auth.AuthResponse": {
    data?: definitions["auth.AuthResponseData"];
    message?: string;
  };
  "auth.AuthResponseData": {
    access_token?: string;
    refresh_token?: string;
  };
  "auth.LoginRequest": {
    password: string;
    username: string;
  };
  "auth.SignupRequest": {
    name: string;
    password: string;
    username: string;
  };
  "health.HealthResponse": {
    db?: string;
    status?: string;
    uptime?: string;
    version?: string;
  };
  "health.ReadinessResponse": {
    checks?: { [key: string]: string };
    status?: string;
  };
  "tasks.CreateTaskRequest": {
    description: string;
    title: string;
  };
  "tasks.TaskResponse": {
    data?: unknown;
    message?: string;
  };
  "utils.Error": {
    error?: string;
    ok?: boolean;
  };
}

export interface operations {}

export interface external {}
